### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by RobsonOL** [RobsonOL/FapesqDashboard#1]
- [ ] Consertar a opção "TODOS" nos dropdownMenu de IES e bolsas.
- [ ] Adicionar página com informações gerais da FAPESQ (about me)
- [ ] Sanitizar as saídas. Exemplo: se a IES não tem doutorado, o tempo de conclusão aparece como NAN meses. Idealmente devia aparecer algum texto.
- [ ] Adicionar gráfico de bolsas no tempo
- [ ] Adicionar novas medidas de produtividade: produção artistica, bibliográfica e técnica. Nesse caso, será que um filtro por área seria interessante? Uma produção como desenvolvimento de software só é relevante para um subconjunto dos programas.
- [ ]  Adicionar mapa para análise regional
- [ ] Adicionar gráficos comparativos entre tipos de bolsas. Exemplo: número de bolsistas FAPESQ x CAPES x OUTROS.
